# Generated by Django 4.1.1 on 2022-10-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declarant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnved',
            name='Ad',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='tnved',
            name='AdditionalMeasureUnit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tnved',
            name='Ex',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='tnved',
            name='F',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='tnved',
            name='Ip',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='tnved',
            name='Sp',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='tnved',
            name='TariffAdvalor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tnved',
            name='TariffSpecific',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tnved',
            name='TariffSpecificAddedToAdvalor',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='tnved',
            name='TariffSpecificCurrency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='tnved',
            name='TariffSpecificMeasureAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='tnved',
            name='TariffSpecificMeasureUnit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
