# Generated by Django 4.1.1 on 2022-11-11 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('declarant', '0002_alter_tnved_ad_alter_tnved_additionalmeasureunit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignmentitem',
            name='xml',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='declarant.xmlmodel'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ContainerXML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContainerId', models.CharField(max_length=17)),
                ('xml', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='declarant.xmlmodel')),
            ],
        ),
    ]
